---
swagger: "2.0"
info:
  description: "This project is a followed tutorial [https://learning-cloud-native-go.github.io/docs/index](https://learning-cloud-native-go.github.io/docs/index). The following reposirtory has the code for building a Dockerized RESTful API Application using Go."
  version: "1.0.0"
  title: "Learning Cloud Native Go"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "tanmay.goyal.pro@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

basePath: "/"
tags:
- name: "user"
  description: "All the possible requests which can be initiated by the user"
schemes:
- "https"
paths:
  //:
    get:
      tags:
      - "user"
      summary: "First Get"
      description: "Initiates the first most basic get request by outputiing hello world"
      operationId: "firstGet"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "string"
  /basicGet:
    get:
      tags:
      - "user"
      summary: "Second Get"
      description: "Initiates the second get request by outputiing a different string"
      operationId: "secondGet"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "string"